  const esc = s => String(s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  // The countries of the site: the code in its address (/fr/...) and its name. One per line.
  const COUNTRIES = [
    { code: 'al', name: 'Albania' },
    { code: 'dz', name: 'Algeria' },
    { code: 'ad', name: 'Andorra' },
    { code: 'ar', name: 'Argentina' },
    { code: 'am', name: 'Armenia' },
    { code: 'au', name: 'Australia' },
    { code: 'at', name: 'Austria' },
    { code: 'az', name: 'Azerbaijan' },
    { code: 'bs', name: 'Bahamas' },
    { code: 'bh', name: 'Bahrain' },
    { code: 'by', name: 'Belarus' },
    { code: 'be', name: 'Belgium' },
    { code: 'ba', name: 'Bosnia and Herzegovina' },
    { code: 'br', name: 'Brazil' },
    { code: 'bg', name: 'Bulgaria' },
    { code: 'kh', name: 'Cambodia' },
    { code: 'ca', name: 'Canada' },
    { code: 'cl', name: 'Chile' },
    { code: 'cn', name: 'China' },
    { code: 'hr', name: 'Croatia' },
    { code: 'cy', name: 'Cyprus' },
    { code: 'cz', name: 'Czech Republic' },
    { code: 'dk', name: 'Denmark' },
    { code: 'eg', name: 'Egypt' },
    { code: 'ee', name: 'Estonia' },
    { code: 'fi', name: 'Finland' },
    { code: 'fr', name: 'France' },
    { code: 'ge', name: 'Georgia' },
    { code: 'de', name: 'Germany' },
    { code: 'gi', name: 'Gibraltar (UK)' },
    { code: 'gr', name: 'Greece' },
    { code: 'gu', name: 'Guam (USA)' },
    { code: 'gg', name: 'Guernsey (UK)' },
    { code: 'hk', name: 'Hong Kong (CN)' },
    { code: 'hu', name: 'Hungary' },
    { code: 'is', name: 'Iceland' },
    { code: 'id', name: 'Indonesia' },
    { code: 'ir', name: 'Iran' },
    { code: 'iq', name: 'Iraq' },
    { code: 'ie', name: 'Ireland' },
    { code: 'il', name: 'Israel' },
    { code: 'it', name: 'Italy' },
    { code: 'jp', name: 'Japan' },
    { code: 'je', name: 'Jersey (UK)' },
    { code: 'kz', name: 'Kazakhstan' },
    { code: 'ke', name: 'Kenya' },
    { code: 'kw', name: 'Kuwait' },
    { code: 'kg', name: 'Kyrgyzstan' },
    { code: 'la', name: 'Laos' },
    { code: 'lv', name: 'Latvia' },
    { code: 'li', name: 'Liechtenstein' },
    { code: 'lt', name: 'Lithuania' },
    { code: 'lu', name: 'Luxembourg' },
    { code: 'my', name: 'Malaysia' },
    { code: 'mt', name: 'Malta' },
    { code: 'mx', name: 'Mexico' },
    { code: 'md', name: 'Moldova' },
    { code: 'mc', name: 'Monaco' },
    { code: 'mn', name: 'Mongolia' },
    { code: 'me', name: 'Montenegro' },
    { code: 'ma', name: 'Morocco' },
    { code: 'nl', name: 'Netherlands' },
    { code: 'nz', name: 'New Zealand' },
    { code: 'mk', name: 'North Macedonia' },
    { code: 'mp', name: 'Northern Mariana Islands (USA)' },
    { code: 'no', name: 'Norway' },
    { code: 'ps', name: 'Palestinian Authority' },
    { code: 'pl', name: 'Poland' },
    { code: 'pt', name: 'Portugal' },
    { code: 'qa', name: 'Qatar' },
    { code: 'ro', name: 'Romania' },
    { code: 'ru', name: 'Russia' },
    { code: 'sm', name: 'San Marino' },
    { code: 'sa', name: 'Saudi Arabia' },
    { code: 'rs', name: 'Serbia' },
    { code: 'sc', name: 'Seychelles' },
    { code: 'sg', name: 'Singapore' },
    { code: 'sk', name: 'Slovakia' },
    { code: 'si', name: 'Slovenia' },
    { code: 'kr', name: 'South Korea' },
    { code: 'es', name: 'Spain' },
    { code: 'se', name: 'Sweden' },
    { code: 'ch', name: 'Switzerland' },
    { code: 'tj', name: 'Tajikistan' },
    { code: 'th', name: 'Thailand' },
    { code: 'tr', name: 'Turkey' },
    { code: 'ae', name: 'UAE' },
    { code: 'us', name: 'USA' },
    { code: 'su', name: 'USSR' },
    { code: 'ua', name: 'Ukraine' },
    { code: 'uk', name: 'United Kingdom' },
    { code: 'uz', name: 'Uzbekistan' },
    { code: 'va', name: 'Vatican' },
    { code: 'vn', name: 'Vietnam' },
    { code: 'ax', name: 'Åland (FI)' },
    { code: 'xx', name: 'Non-recognized and partially recognized states' }
  ];
  const cName = code => { const c = COUNTRIES.find(x => x.code === code); return c ? c.name : String(code).toUpperCase(); };
  const uid = () => (window.crypto && crypto.randomUUID) ? crypto.randomUUID() : Date.now() + '-' + Math.random().toString(36).slice(2);
